# Generated by Django 3.1.5 on 2021-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, unique=True)),
                ('l_name', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('book_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
