# Generated by Django 3.1.5 on 2021-06-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='f_name',
            new_name='auth_name',
        ),
        migrations.RemoveField(
            model_name='books',
            name='l_name',
        ),
    ]
